# Generated by Django 4.1.5 on 2023-05-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docleave',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docleave', to='api.doctorprofile'),
        ),
    ]
